### ISSUE TITLE
Sam should open some more issues so I can contribute to this project

### ISSUE THREAD

**Issue by jfox13-nd** [sambattalio/gameboy#14]
Inattentive FOSS dev 🚀

**Comment by sambattalio** [comment]
I will open more issues I guess tonight

**Comment by sambattalio** [comment]
Calling all hot shot Silicon Valley engineers (@jfox13-nd @ginglis13). I am willing to pay you in exposure to help with this hot new south bend startup. If you want, you can grab a command from the manual (linked in README) and implement it in proc.c across all of its opcodes. Some of them are pretty weird and can be googled, but others are pretty staightforward (like setting a flag or something). A good place to start might be rotates and shifts, which could help you get used to the struct and massive file setup. Bravo Zulu brothers.
