### ISSUE TITLE
 RES b,r

### ISSUE THREAD

**Issue by sambattalio** [sambattalio/gameboy#16]
opcodes: CB 80-87.

Desc: Reset bit b in register r. (based on opcode)

page 110 of the realboy manual on readme.

**Comment by mdadamio** [comment]
@sambattalio please fix this immediately

**Comment by sambattalio** [comment]
This is a great opportunity for a community PR! If you would like to help please let me know and I can assign you! 📈 🚀

**Comment by ginglis13** [comment]
@sambattalio do these just require a new case in the instruction handler in `proc.c`?

**Comment by sambattalio** [comment]
The cases should be autogen'd already with some flag stuff already set (if its just 1 or 0 automatically thanks to @noyoshi). You can just ctrl-f the opcode (eg. 0x71) and the comment should match the instruction

**Comment by ginglis13** [comment]
I'd like to take this jawn on if that's cool, or another one if @mdadamio is hitting this boi up

**Comment by sambattalio** [comment]
Closed thanks to community contributor @ginglis13 (future amazon engineer btw) 🚀
