### ISSUE TITLE
Yo here's how you use p->registers

### ISSUE THREAD

**Issue by sambattalio** [sambattalio/gameboy#23]
When you access a register, you only need to set or use the variable p->registers.(whatever). You use memory only when you have the parentheses. My bad for not checking that earlier.
@ginglis13 @jfox13-nd 

Im going back and fixing ur stuff though so don't worry about pulled stuff that's my b.

**Comment by ginglis13** [comment]
ah gotcha, that makes sense. will be more careful in the future, o7

**Comment by sambattalio** [comment]
ye no worries. I shoulda been more vigilant in my code reviewing
